import { useScrollAnimation } from "@/hooks/use-scroll-animation";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { AlertTriangle, Radio, Shield, Zap, Ghost, Signal, Target } from "lucide-react";

const storyElements = [
  {
    icon: AlertTriangle,
    title: "The Villain",
    subtitle: "The Noise",
    description: "By 2026, AI sales agents will generate 99% of all emails. Human buyers will block everything. The 'Outbound Wasteland' is coming.",
    accent: "#FF6600",
  },
  {
    icon: Signal,
    title: "The Guide",
    subtitle: "Signal Processor",
    description: "Symmetri isn't just a tool; it's a Signal Processor. We cut through the AI noise to find the human pulse.",
    accent: "#FFB800",
  },
  {
    icon: Target,
    title: "The Stakes",
    subtitle: "Adapt or Vanish",
    description: "Adapt to Autonomous Revenue, or get filtered out. There's no middle ground in 2026.",
    accent: "#FF4400",
  },
];

function NoiseVisualization() {
  return (
    <div className="relative h-40 overflow-hidden rounded-xl bg-[#0a0a0a] border border-white/10">
      {/* Noise particles representing spam emails */}
      <div className="absolute inset-0">
        {[...Array(50)].map((_, i) => (
          <div
            key={i}
            className="absolute text-xs font-mono text-white/10"
            style={{
              left: `${Math.random() * 100}%`,
              top: `${Math.random() * 100}%`,
              animation: `drift ${5 + Math.random() * 5}s linear infinite`,
              animationDelay: `${Math.random() * 5}s`,
            }}
          >
            {["@", "#", "$", "%", "&", "*", "!", "?"][Math.floor(Math.random() * 8)]}
          </div>
        ))}
      </div>
      
      {/* Signal beam cutting through - Labs gradient */}
      <div 
        className="absolute left-0 right-0 h-1 bg-gradient-to-r from-transparent via-[#FFB800] to-transparent top-1/2 -translate-y-1/2"
        style={{
          animation: "pulseWidth 2s ease-in-out infinite",
        }}
      />
      
      {/* Ghost icons representing filtered buyers */}
      <div className="absolute inset-0 flex items-center justify-center gap-8">
        <Ghost className="w-8 h-8 text-white/5" />
        <Radio className="w-10 h-10 text-[#FFB800] animate-pulse" />
        <Ghost className="w-8 h-8 text-white/5" />
      </div>
      
      <style>{`
        @keyframes drift {
          0% { transform: translateY(0) translateX(0); opacity: 0.1; }
          50% { opacity: 0.3; }
          100% { transform: translateY(-100px) translateX(20px); opacity: 0; }
        }
        @keyframes pulseWidth {
          0%, 100% { opacity: 0.3; transform: scaleX(0.5) translateY(-50%); }
          50% { opacity: 1; transform: scaleX(1) translateY(-50%); }
        }
      `}</style>
    </div>
  );
}

export function SilenceOfSection() {
  const { ref, isVisible } = useScrollAnimation<HTMLElement>();

  return (
    <section 
      ref={ref}
      className="relative py-20 sm:py-28 px-4 sm:px-6 lg:px-8 overflow-hidden bg-[#050505]"
      data-testid="silence-of-section"
    >
      <div className="max-w-6xl mx-auto relative z-10">
        <div className={`text-center mb-16 animate-on-scroll ${isVisible ? "visible" : ""}`}>
          <Badge 
            variant="outline" 
            className="border-[#FFB800]/50 text-[#FFB800] bg-[#0a0a0a] px-4 py-1.5 text-sm font-medium mb-6"
          >
            <Radio className="w-4 h-4 mr-2" />
            The Silence of 2026
          </Badge>
          
          <h2 className="text-3xl sm:text-4xl lg:text-6xl font-bold mb-6">
            <span className="text-white">The Inbox is Dead.</span>
            <br />
            <span className="bg-gradient-to-r from-[#FFB800] via-[#FF9900] via-[#FF6600] to-[#FF4400] bg-clip-text text-transparent">Long Live the Signal.</span>
          </h2>
          
          <p className="text-xl text-white/80 max-w-3xl mx-auto">
            Most B2B companies are still solving yesterday's problem: getting more leads. 
            The future demands something else entirely.
          </p>
        </div>
        
        {/* Noise Visualization */}
        <div className={`mb-16 animate-on-scroll ${isVisible ? "visible" : ""} delay-100`}>
          <NoiseVisualization />
          <p className="text-center text-sm text-white/50 mt-4 font-mono">
            99% of outreach will be AI-generated by 2026 — humans will filter everything
          </p>
        </div>
        
        {/* Story Arc Cards */}
        <div className={`grid md:grid-cols-3 gap-6 animate-on-scroll ${isVisible ? "visible" : ""} delay-200`}>
          {storyElements.map((element, index) => {
            const Icon = element.icon;
            return (
              <Card 
                key={element.title}
                className="bg-[#0a0a0a] border-white/10 hover:border-white/20 transition-all duration-300 group"
                data-testid={`story-card-${index}`}
              >
                <CardContent className="p-6">
                  <div 
                    className="w-12 h-12 rounded-xl flex items-center justify-center mb-4 transition-transform group-hover:scale-110 bg-[#0f0f0f]"
                  >
                    <Icon className="w-6 h-6" style={{ color: element.accent }} />
                  </div>
                  
                  <div className="text-xs font-mono text-white/50 mb-1">{element.title}</div>
                  <h3 
                    className="text-xl font-bold mb-3"
                    style={{ color: element.accent }}
                  >
                    {element.subtitle}
                  </h3>
                  <p className="text-white/70 leading-relaxed">
                    {element.description}
                  </p>
                </CardContent>
              </Card>
            );
          })}
        </div>
        
        {/* Call to action message */}
        <div className={`text-center mt-16 animate-on-scroll ${isVisible ? "visible" : ""} delay-300`}>
          <div className="inline-flex items-center gap-3 px-6 py-3 rounded-full bg-[#0a0a0a] border border-white/10">
            <Shield className="w-5 h-5 text-[#FFB800]" />
            <span className="text-white font-medium">
              Symmetri transforms your outreach into a 
              <span className="bg-gradient-to-r from-[#FFB800] to-[#FF4400] bg-clip-text text-transparent font-bold ml-1">signal that cuts through</span>
            </span>
            <Zap className="w-5 h-5 text-[#FF9900]" />
          </div>
        </div>
      </div>
    </section>
  );
}
